/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework2;


public class dashboardUser extends javax.swing.JFrame {

    
    public dashboardUser() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        lable1 = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        lable3 = new javax.swing.JLabel();
        lable4 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        textff = new javax.swing.JTextField();
        but3 = new javax.swing.JPanel();
        lable5 = new javax.swing.JLabel();
        lable6 = new javax.swing.JLabel();
        lable7 = new javax.swing.JLabel();
        lable8 = new javax.swing.JLabel();
        lable9 = new javax.swing.JLabel();
        lable10 = new javax.swing.JLabel();
        lable11 = new javax.swing.JLabel();
        lable12 = new javax.swing.JLabel();
        lable13 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        text8 = new javax.swing.JTextField();
        text9 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();
        text11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lable15 = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        lable16 = new javax.swing.JLabel();
        text12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        tf1.setBackground(new java.awt.Color(0, 153, 153));
        tf1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 255, 255));
        tf1.setText("Accounting -A71");

        lable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 255, 255));
        lable1.setText("Wazarat");

        lable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable2.setForeground(new java.awt.Color(255, 255, 255));
        lable2.setText("Farmanga");

        lable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable3.setForeground(new java.awt.Color(255, 255, 255));
        lable3.setText("Barwari Dawakari");

        lable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable4.setForeground(new java.awt.Color(255, 255, 255));
        lable4.setText("Barwari Froshtn");

        text1.setBackground(new java.awt.Color(0, 153, 153));
        text1.setForeground(new java.awt.Color(255, 255, 255));

        text2.setBackground(new java.awt.Color(0, 153, 153));
        text2.setForeground(new java.awt.Color(255, 255, 255));

        textff.setBackground(new java.awt.Color(0, 153, 153));
        textff.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        textff.setForeground(new java.awt.Color(255, 255, 255));
        textff.setText("Balganamai Wargrtn U Kharji Rastawkho");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lable2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lable4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lable3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(textff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable3)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable2)
                    .addComponent(lable4))
                .addContainerGap())
        );

        but3.setBackground(new java.awt.Color(153, 153, 255));

        lable5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable5.setForeground(new java.awt.Color(255, 255, 255));
        lable5.setText("Nawe Froshyar");

        lable6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable6.setForeground(new java.awt.Color(255, 255, 255));
        lable6.setText("Shweni Froshyar");

        lable7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable7.setForeground(new java.awt.Color(255, 255, 255));
        lable7.setText("Naw & jori kalupal");

        lable8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable8.setForeground(new java.awt.Color(255, 255, 255));
        lable8.setText("Yakai Pewar");

        lable9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable9.setForeground(new java.awt.Color(255, 255, 255));
        lable9.setText("Zhmara");

        lable10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable10.setForeground(new java.awt.Color(255, 255, 255));
        lable10.setText("Nrkhi Tak");

        lable11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable11.setForeground(new java.awt.Color(255, 255, 255));
        lable11.setText("Koyi Gshty");

        lable12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable12.setForeground(new java.awt.Color(255, 255, 255));
        lable12.setText("Tebini");

        lable13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable13.setForeground(new java.awt.Color(255, 255, 255));
        lable13.setText("Nawi Wargr");

        text3.setBackground(new java.awt.Color(0, 153, 153));
        text3.setForeground(new java.awt.Color(255, 255, 255));

        text4.setBackground(new java.awt.Color(0, 153, 153));
        text4.setForeground(new java.awt.Color(255, 255, 255));

        text5.setBackground(new java.awt.Color(0, 153, 153));
        text5.setForeground(new java.awt.Color(255, 255, 255));

        text6.setBackground(new java.awt.Color(0, 153, 153));
        text6.setForeground(new java.awt.Color(255, 255, 255));

        text7.setBackground(new java.awt.Color(0, 153, 153));
        text7.setForeground(new java.awt.Color(255, 255, 255));

        text8.setBackground(new java.awt.Color(0, 153, 153));
        text8.setForeground(new java.awt.Color(255, 255, 255));

        text9.setBackground(new java.awt.Color(0, 153, 153));
        text9.setForeground(new java.awt.Color(255, 255, 255));

        text10.setBackground(new java.awt.Color(0, 153, 153));
        text10.setForeground(new java.awt.Color(255, 255, 255));

        text11.setBackground(new java.awt.Color(0, 153, 153));
        text11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ganginadar");

        lable15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable15.setForeground(new java.awt.Color(255, 255, 255));
        lable15.setText("Barwar");

        but1.setBackground(new java.awt.Color(0, 153, 153));
        but1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but1.setForeground(new java.awt.Color(255, 255, 255));
        but1.setText("Insert");

        but2.setBackground(new java.awt.Color(0, 153, 153));
        but2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but2.setForeground(new java.awt.Color(255, 255, 255));
        but2.setText("Clear");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 153, 153));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        lable16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lable16.setForeground(new java.awt.Color(255, 255, 255));
        lable16.setText("Barwar");

        text12.setBackground(new java.awt.Color(0, 153, 153));
        text12.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout but3Layout = new javax.swing.GroupLayout(but3);
        but3.setLayout(but3Layout);
        but3Layout.setHorizontalGroup(
            but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but3Layout.createSequentialGroup()
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(but1)
                        .addGap(104, 104, 104)
                        .addComponent(but2)
                        .addGap(107, 107, 107)
                        .addComponent(Exit))
                    .addGroup(but3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lable13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(text7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(text10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(but3Layout.createSequentialGroup()
                                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(text12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lable15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable16))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        but3Layout.setVerticalGroup(
            but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable5)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable8))
                .addGap(18, 18, 18)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable9)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lable10)
                            .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lable11))
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lable12)
                    .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lable13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lable15)
                        .addGap(18, 18, 18)
                        .addComponent(lable16))
                    .addGroup(but3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(text12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but1)
                    .addComponent(but2)
                    .addComponent(Exit))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
       text1.setText("");
          text2.setText("");
           text3.setText("");
           text4.setText("");
          text5.setText("");
          text6.setText("");
          text7.setText("");
           text8.setText("");
           text9.setText("");
          text10.setText("");
           text11.setText("");
          text12.setText("");
    }//GEN-LAST:event_but2ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
      this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logExit.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JPanel but3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable10;
    private javax.swing.JLabel lable11;
    private javax.swing.JLabel lable12;
    private javax.swing.JLabel lable13;
    private javax.swing.JLabel lable15;
    private javax.swing.JLabel lable16;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JLabel lable4;
    private javax.swing.JLabel lable5;
    private javax.swing.JLabel lable6;
    private javax.swing.JLabel lable7;
    private javax.swing.JLabel lable8;
    private javax.swing.JLabel lable9;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text11;
    private javax.swing.JTextField text12;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text9;
    private javax.swing.JTextField textff;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
